update=21/05/2018 07:03:48
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=sensor.net
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.09999999999999999
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=lib/less-smog
LibName2=C:/Program Files/KiCad/share/kicad/library/device
LibName3=C:/Program Files/KiCad/share/kicad/library/power
LibName4=C:/Program Files/KiCad/share/kicad/library/conn
LibName5=C:/Program Files/KiCad/share/kicad/library/switches
LibName6=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName7=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName8=C:/Program Files/KiCad/share/kicad/library/74xx
LibName9=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName10=C:/Program Files/KiCad/share/kicad/library/actel
LibName11=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName12=C:/Program Files/KiCad/share/kicad/library/allegro
LibName13=C:/Program Files/KiCad/share/kicad/library/Altera
LibName14=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName15=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName16=C:/Program Files/KiCad/share/kicad/library/atmel
LibName17=C:/Program Files/KiCad/share/kicad/library/audio
LibName18=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName19=C:/Program Files/KiCad/share/kicad/library/bbd
LibName20=C:/Program Files/KiCad/share/kicad/library/bosch
LibName21=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName22=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName23=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName24=C:/Program Files/KiCad/share/kicad/library/contrib
LibName25=C:/Program Files/KiCad/share/kicad/library/cypress
LibName26=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName27=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName28=C:/Program Files/KiCad/share/kicad/library/diode
LibName29=C:/Program Files/KiCad/share/kicad/library/display
LibName30=C:/Program Files/KiCad/share/kicad/library/dsp
LibName31=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName32=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName33=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName34=C:/Program Files/KiCad/share/kicad/library/gennum
LibName35=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName36=C:/Program Files/KiCad/share/kicad/library/hc11
LibName37=C:/Program Files/KiCad/share/kicad/library/infineon
LibName38=C:/Program Files/KiCad/share/kicad/library/intel
LibName39=C:/Program Files/KiCad/share/kicad/library/interface
LibName40=C:/Program Files/KiCad/share/kicad/library/intersil
LibName41=C:/Program Files/KiCad/share/kicad/library/ir
LibName42=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName43=C:/Program Files/KiCad/share/kicad/library/leds
LibName44=C:/Program Files/KiCad/share/kicad/library/LEM
LibName45=C:/Program Files/KiCad/share/kicad/library/linear
LibName46=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName47=C:/Program Files/KiCad/share/kicad/library/maxim
LibName48=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName49=C:/Program Files/KiCad/share/kicad/library/memory
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName52=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName53=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName54=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName55=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName56=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName57=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName58=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName59=C:/Program Files/KiCad/share/kicad/library/modules
LibName60=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName61=C:/Program Files/KiCad/share/kicad/library/motorola
LibName62=C:/Program Files/KiCad/share/kicad/library/motors
LibName63=C:/Program Files/KiCad/share/kicad/library/msp430
LibName64=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName65=C:/Program Files/KiCad/share/kicad/library/nxp
LibName66=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName67=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName68=C:/Program Files/KiCad/share/kicad/library/opto
LibName69=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName70=C:/Program Files/KiCad/share/kicad/library/philips
LibName71=C:/Program Files/KiCad/share/kicad/library/powerint
LibName72=C:/Program Files/KiCad/share/kicad/library/pspice
LibName73=C:/Program Files/KiCad/share/kicad/library/references
LibName74=C:/Program Files/KiCad/share/kicad/library/regul
LibName75=C:/Program Files/KiCad/share/kicad/library/relays
LibName76=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName77=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName78=C:/Program Files/KiCad/share/kicad/library/sensors
LibName79=C:/Program Files/KiCad/share/kicad/library/silabs
LibName80=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName81=C:/Program Files/KiCad/share/kicad/library/stm8
LibName82=C:/Program Files/KiCad/share/kicad/library/stm32
LibName83=C:/Program Files/KiCad/share/kicad/library/supertex
LibName84=C:/Program Files/KiCad/share/kicad/library/texas
LibName85=C:/Program Files/KiCad/share/kicad/library/transf
LibName86=C:/Program Files/KiCad/share/kicad/library/transistors
LibName87=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName88=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName89=C:/Program Files/KiCad/share/kicad/library/valves
LibName90=C:/Program Files/KiCad/share/kicad/library/video
LibName91=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName92=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName93=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName94=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName95=C:/Program Files/KiCad/share/kicad/library/zetex
LibName96=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName97=D:/test/kicadLib/niceRLC
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=56
